services:
  spring:
    # ECR로부터 Spring Boot 이미지를 pull 받아 컨테이너 실행
    image: 063355381577.dkr.ecr.ap-northeast-2.amazonaws.com/pium/repo:latest
    restart: always
    ports:
      - "8080:8080"
#    env_file:
#      - .env
    environment:
      SPRING_DB_ENDPOINT: ${SPRING_DB_ENDPOINT}
      SPRING_DB_USERNAME: ${SPRING_DB_USERNAME}
      SPRING_DB_PASSWORD: ${SPRING_DB_PASSWORD}
      SPRING_REDIS_ENDPOINT: ${SPRING_REDIS_ENDPOINT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_AWS_ACCESS_KEY: ${SPRING_AWS_ACCESS_KEY}
      SPRING_AWS_SECRET_KEY: ${SPRING_AWS_SECRET_KEY}
      SPRING_S3_AWS_ACCESS_KEY: ${SPRING_S3_AWS_ACCESS_KEY}
      SPRING_S3_AWS_SECRET_KEY: ${SPRING_S3_AWS_SECRET_KEY}
      SPRING_JWT_SECRET_KEY: ${SPRING_JWT_SECRET_KEY}
      SPRING_PROFILES_ACTIVE: prod
    container_name: pium-spring
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - elk  # elk 네트워크에 연결


  # Logstash 서비스 - 로그 수집, 변환, 전송 파이프라인
  logstash:
    image: docker.elastic.co/logstash/logstash:8.11.0  # Logstash 8.11.0 이미지 사용
    container_name: logstash  # 컨테이너 이름 지정
    environment:
      - "LS_JAVA_OPTS=-Xmx512m -Xms512m"  # Logstash JVM 메모리 설정 (512MB)
    volumes:
      # Logstash 설정 파일들을 컨테이너에 마운트 (읽기 전용)
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro  # 파이프라인 설정 파일들
      - ./logs:/usr/share/logstash/logs:ro # 로그 파일
    ports:
      - "5044:5044"    # Beats 입력 포트 (Filebeat, Metricbeat 등)
      - "5050:5050/tcp"  # TCP 로그 입력 포트
      - "5050:5050/udp"  # UDP 로그 입력 포트
      - "9600:9600"    # Logstash API 포트 (모니터링용)
    networks:
      - elk  # elk 네트워크에 연결

    # 헬스체크 추가
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9600" ]
      interval: 30s
      timeout: 10s
      retries: 5
    # Elasticsearch가 완전히 준비될 때까지 대기
    restart: unless-stopped

  # Kibana 서비스 - 데이터 시각화 및 대시보드 웹 인터페이스
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0  # Kibana 8.11.0 이미지 사용
    container_name: kibana  # 컨테이너 이름 지정
    environment:
      - ELASTICSEARCH_HOSTS=http://43.203.128.119:9200  # Elasticsearch 연결 주소
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - elk

  # Filebeat - 시스템 로그 수집
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: filebeat
    user: root
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro # Filebeat 설정파일
      - ./logs:/usr/share/filebeat/logs # Spring Boot 로그 파일 (애플리케이션과 공유)
    depends_on:
      - logstash
    networks:
      - elk

  # S3 백업 전용 컨테이너 (스크립트 기반 - 안정적)
  backup:
    image: alpine:latest
    container_name: backup
    environment:
      - AWS_ACCESS_KEY_ID=${S3_AWS_ACCESS_KEY}
      - AWS_SECRET_ACCESS_KEY=${S3_AWS_SECRET_KEY}
      - S3_BUCKET= pium-image-bucket
      - S3_PREFIX= elk-logs
    volumes:
      - ./logs:/logs
    restart: unless-stopped
    command: |
      sh -c '
       apk add --no-cache aws-cli dcron
      
        # 한 번에 모든 크론 작업 설정
        # 30분마다 .gz 파일 체크 후 s3업로드(테스트)
        # 새벽 2시마다 7일이상 지난 파일 정리
        # 디스크 사용량 80% 이상시 긴급 정리 (매시간 체크)
        echo "*/30 * * * * find /logs -name \"*.gz\" -exec aws s3 cp {} s3://'"$$S3_BUCKET"'/'"$$S3_PREFIX"'/\$(date +%Y/%m/%d)/ \; -delete
        0 2 * * * find /logs -name \"*.log\" -mtime +7 -delete; find /logs -type d -empty -delete  
        0 * * * * [ \$(df /logs | awk \"NR==2 {print \\\$5}\" | sed \"s/%//\") -gt 80 ] && find /logs -name \"*.log\" -mtime +3 -delete" | crontab -
      
        echo "All cron jobs configured:"
        crontab -l
      
        crond && tail -f /dev/null
      '
    networks:
      - elk

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"                    # 외부 접속용 포트 (Spring Boot에서 사용)
      - "9101:9101"                    # JMX 모니터링 포트
    networks:
      - elk
    volumes:
      - kafka_data:/var/lib/kafka/data
    environment:
      # 노드 정보 설정
      KAFKA_NODE_ID: 1                 # 노드 고유 ID (클러스터 내 유일해야 함)
      KAFKA_PROCESS_ROLES: 'broker,controller'  # 이 노드가 브로커와 컨트롤러 역할 둘 다 수행
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'     # 클러스터 고유 ID (변경 가능)
      # 리스터 설정
      # 각 리스너의 보안 프로토콜 정의 (개발용이라 모두 PLAINTEXT)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      # - PLAINTEXT: 컨테이너 내부 통신용 (29092)
      # - CONTROLLER: KRaft 컨트롤러 통신용 (29093)
      # - PLAINTEXT_HOST: 외부 접속용 (9092)
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      # 클라이언트에게 알려줄 주소들 -> 컨테이너 내부는 29092, 외부에서는 localhost:9092로 접속
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'      # 브로커 간 통신에 사용할 리스너
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'      # 컨트롤러 통신에 사용할 리스너
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'    # 컨트롤러 투표 참여자 (노드1이 29093 포트)
      # === 토픽 및 복제 설정 ===
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1          # __consumer_offsets 토픽 복제 팩터 (단일 브로커라 1)
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'            # 토픽 자동 생성 허용
      # === 성능 및 안정성 설정 ===
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0          # 컨슈머 그룹 리밸런싱 지연시간 (개발용 0)
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'          # 로그 파일 저장 경로
    healthcheck:
      test: [ "CMD-SHELL", "kafka-broker-api-versions --bootstrap-server kafka:29092" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # Kafka UI (선택사항 - 관리 편의성을 위해)
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - elk
    ports:
      - "28080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "docker-local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:29092"
    depends_on:
      kafka:
        condition: service_healthy

volumes:
  kafka_data:
    driver: local
networks:
  elk: # ELK가 서로 네트워크 상에서 통신할 수 있게 도와줌
    driver: bridge # 기본 브리지 네트워크 방식 사용
