name: cd-dev

on:
  create:
    branches:
      - release

env:
  AWS_REGION: ap-northeast-2
  S3_BUCKET_NAME: pium-deploy-bucket
  CODE_DEPLOY_APPLICATION_NAME: pium-dev
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: pium-deploy-group

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew clean build -x test

      - name: Rename JAR file to app.jar
        run: |
          JAR_PATH=$(find build/libs -name "*.jar" | head -n 1)
          echo "Found JAR: $JAR_PATH"
          cp "$JAR_PATH" app.jar

      - name: Create .env file
        env:
          ENV_PATH: .env
        run: |
          touch $ENV_PATH
          echo DB_ENDPOINT=${{ secrets.DB_ENDPOINT }} >> $ENV_PATH
          echo DB_USERNAME=${{ secrets.DB_USERNAME }} >> $ENV_PATH
          echo DB_PASSWORD=${{ secrets.DB_PASSWORD }} >> $ENV_PATH
          echo REDIS_ENDPOINT=${{ secrets.REDIS_ENDPOINT }} >> $ENV_PATH
          echo REDIS_HOST=${{ secrets.DEV_REDIS_HOST }} >> $ENV_PATH
          echo MAIL_USERNAME=${{ secrets.MAIL_USERNAME }} >> $ENV_PATH
          echo MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }} >> $ENV_PATH
          echo AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} >> $ENV_PATH
          echo AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }} >> $ENV_PATH
          echo JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} >> $ENV_PATH
          

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: pium/repo
          IMAGE_TAG: latest
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Upload to S3
        run: |
          zip -r ./$GITHUB_SHA.zip ./scripts appspec.yml release-docker-compose.yml .env logstash/
          aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.zip s3://$S3_BUCKET_NAME

      - name: Deploy to EC2 with CodeDeploy
        run: |
          aws deploy create-deployment \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,key=$GITHUB_SHA.zip,bundleType=zip
